Update from master
* Parallelise .travis.yml to speed up CI

This is an attempt to parallelize Travis to speed up the CI by splitting up the different tests

* Update travis.yml with names and merge build, doc & coveralls

 - Adds names to jobs
 - Merges the 3 fastest stages (Build, Doc & Coveralls) to reduce system load
 - Fixes Coveralls by running it after build script

* Splitting off Doc job again

Splitting off Doc job again since it's now the bottleneck

* Correct incorrect RU addressing introduced in PR848

RU addressing during filteirng in PR 848 works by accident; it assumes
stripes are the same size as the RU, which is not the case (but
currently true in the hardwired test code)

* Correct RestorationState setup addressing bug/removals from PR 848

PR 848 removed some of the RestorationPlane setup needed once RU != SB
In addition, the sb_log2 calculation was incorrect (but worked with current settings)

* Bypass filtering of strengh=0 cdef blocks for speed.

* For hbd use scalar code for subpel (#857)

* Clarify stripe addressing in lrf

Eliminate the passing of a PlaneConfig to stripe addressing, add a
documented field for strip height.

* Early termination for bottomup partition search (i.e. speed 0 only) (#858)

This works for speed 0 (i.e. bottomup partition search) only.

Almost no change in bdrate with more than x2 faster for large QIndex 252
with no change in its bitstream size.

* Simplify inverse txfm code (#860)

* Revert "Bypass filtering of strengh=0 cdef blocks for speed."

This reverts commit df6793dea9df790ee4393a836ec3b44944fe3121.

* Use unreachable macro for mc asm code (#865)

* Skip rust format for quantization data (#867)

* Format some very long lines of code (#866)

Format some very long lines of code

* Format uncompressed header writing code (#868)

* Switch nasm-rs to release

* Bump dav1d-rs and bindgen versions to be the same 

Fixes #871.

* Add and hookup inverse txfm assembly (#864)

Roughly a 10% speedup.
https://beta.arewecompressedyet.com/?job=master67477ddb5%402019-01-17T15%3A18%3A16.747Z&job=hookup_simd_inv_txfm%402019-01-20T15%3A07%3A53.951Z

* Automated aarch64 builds in AppVeyor (#854)

* Update to VS17 preview and specify build environment

* Upload all .exe files in target\release as artifact

* Allow failures on arm64 and not x86_64

* Deploy artifacts to GitHub on release (like 0.1.1)

* Enable deploy to GitHub on relase

* Add AppVeyor status badge to Readme

* Work buffer setup refactor in CDEF RDO

Break out some of the buffered work frame setup code for CDEF in prep for
using it along with LRF.
Also update the code in question to handle 128x128 superblocks as we're
there anyway.

* Fix to LRF cropping

Recent simplification that eliminated clipped_cfg broke the loop
restoration filters and I didn't notice as it's not enabled by default yet.
This fixes the cropping for chroma in the SGR and Wiener filters.

* Workaround fix for earlyexit of bottomup partition search (#876)

Enable early-exit of bottomup partition search (i.e speed 0) for PARTITION_SPLIT only
and don't do early-exit with PARTITOIN_HORZ or PARTITION_VERT.
This will lead to no change in bdrate.

Most of the speed gain is preserved.

* Deduplicate checkpoint() calls in rdo_partition_decision() (#861)

Call checkpoint() only once right before the loop starts in
rdo_partition_decision().
There is some minor speed gain with no change in bdrate.

* Revert 2c2777dc462e6385678a6e699fa04ffeea336371 -- breaks decode tests

The fix to #871 breaks decode unit tests, that is:

cargo test --release --features=decode_test

fails either with a segfault or an indefinite spin.  I got no useful error output, but TD gets:

error: failed to run custom build command for `rav1e v0.1.0 (/home/thomas/sandbox/xav1)`
process didn't exit successfully: `/home/thomas/sandbox/xav1/target/release/build/rav1e-50bde2c63e94b5ba/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)

Looks like a bug i new bindgen?

* Do not build aom examples and tools

* Early termination for topdown partition (#859)

* Implement lookahead queue

Allows rav1e to read frames into the frame queue ahead of the current
one, to allow for future features to be added that depend on a lookahead
pass. Currently the lookahead distance is hardcoded to 10. In the
future, this would probably be configurable as a CLI option.

* Split the high bd tests

* Fix the comparison function for high bd

* Import enum values for simple match blocks (#884)

* Improve bottomup partition search code (#883)

Improve bottomup partition search code

- Don't use Option when returning the result
- Don't use modes vector but use main rdo_output struct

* Add a enable_early_exit flag under fi (#885)

Its value is set as true by default.

* Add Clippy to CI

* The rdo_mode_decision() returns RDOPartitionOutput struct only (#889)

This also makes it possiblt to remove all .clone() calls to
the return value of rdo_mode_decision().